apiVersion: v1
kind: Service
metadata:
  name: {{ include "muc.fullname" . }}-edge
  labels:
    app.kubernetes.io/component: edge
    {{- include "muc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: edge
    {{- include "muc.selectorLabels" . | nindent 4 }}
