apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muc.fullname" . }}-wui
  labels:
    app.kubernetes.io/component: wui
    {{- include "muc.labels" . | nindent 4 }}
data:
  config.json: '{"edge": "wss://{{ .Values.ingress.edge.host}}" }'
