{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "muc.fullname" . }}-wui
  labels:
    app.kubernetes.io/component: wui
    {{- include "muc.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.wui.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "muc.fullname" . }}-wui
              servicePort: {{ .Values.service.port }}
{{- end }}
